FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y gcc g++ libpq-dev python3-dev curl

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app
COPY app .

RUN useradd -m -s /bin/bash -G sudo user
RUN chown -R user:user /app
RUN chmod -R 775 /app
USER user

EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]
CMD ["runserver"]


